name: Simple Docker Build and Push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_gabrydark18 }}
          password: ${{ secrets.DOCKERHUB_dckr_pat_CYAMybnFhFteLxyKchOUpXRrzqs }}
      
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_gabrydark18 }}/my-app:latest .
      
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_gabrydark18 }}/my-app:latest

